INSERT INTO university (name) VALUES
('Aberystwyth University'),
('Academy of Contemporary Music'),
('Academy of Live and Recorded Arts'),
('Aga Khan University, Aga Khan University'),
('Al-Maktoum Institute for Arabic and Islamic Studies'),
('All Nations Christian College'),
('Alpha Meridian College, Greenwich'),
('American InterContinental University, London'),
('American University in London (AUL), London'),
('Anglia Ruskin University'),
('Anglo-European College of Chiropractic'),
('Architectural Association School of Architecture'),
('Arts Educational Schools, London'),
('Asanté Academy of Chinese Medicine'),
('Ashridge Business School'),
('Aston University, Birmingham'),
('Azad University IR in Oxford'),
('Bangor University'),
('Baptist Union of Great Britain'),
('Bath Spa University'),
('Bird College'),
('Birmingham Christian College'),
('Birmingham City University'),
('Birmingham International College'),
('Bishop Grosseteste University'),
('Blackburne House'),
('Blake Hall College'),
('Booth School of Business'),
('Boston University'),
('Bournemouth University'),
('BPP University College of Professional Studies'),
('Brighton and Sussex Medical School'),
('Brighton Institute of Modern Music'),
('British College of Osteopathic Medicine'),
('British Institute of Technology & E-commerce'),
('British School of Osteopathy'),
('Brunel University'),
('Buckinghamshire New University, High Wycombe'),
('Canterbury Christ Church University'),
('Cardiff Metropolitan University (UWIC)'),
('Cardiff University'),
('City and Guilds of London Art School'),
('City of London Academy'),
('City University, London'),
('College of Accountancy and Management Studies, Hayes, Hillingdon'),
('College of Estate Management, Reading, Berkshire'),
('College of the Resurrection, Mirfield'),
('Conservatoire for Dance and Drama'),
('Coventry University'),
('Cranfield University, Cranfield, Shrivenham and Silsoe'),
('De Montfort University, Leicester'),
('Durham University'),
('eCollege London'),
('Edge Hill University, Ormskirk, Lancashire'),
('Edinburgh College of Art'),
('Edinburgh Napier University'),
('EF Brittin College Manchester'),
('English National Ballet School'),
('EThames Graduate School'),
('European School of Osteopathy'),
('Fairleigh Dickinson University, Oxfordshire'),
('Falmouth University'),
('Futureworks Media School, Manchester'),
('Girne American University, Canterbury'),
('Glasgow Caledonian University'),
('Glasgow School of Art'),
('Glyndwr University, Wrexham'),
('Grafton College of Management Sciences, London'),
('Greenwich School of Management'),
('Guildford School of Acting'),
('Guildhall School of Music and Drama'),
('Halifax Group of Colleges'),
('Hamilton College, London'),
('Harper Adams University, Newport, Shropshire'),
('Hartpury College'),
('Heriot-Watt University'),
('Holborn College'),
('Hull York Medical School (HYMS)'),
('Hult International Business School'),
('Impact International College'),
('Imperial College London'),
('Institute for System Level Integration'),
('International College Scotland'),
('Irish School of Ecumenics, postgraduate institute of Trinity College'),
('Keele University, Staffordshire'),
('Kingston University'),
('Lancaster University'),
('Leeds College of Art'),
('Leeds College of Business Management and Technology'),
('Leeds College of Music'),
('Leeds Metropolitan University'),
('Leeds Professional College'),
('Leeds Trinity University, Horsforth, Leeds'),
('Liverpool Hope University'),
('Liverpool Institute for Performing Arts'),
('Liverpool John Moores University'),
('London Academy of Management Sciences'),
('London College of Advanced Studies'),
('London College of Business & Computing'),
('London College of Management Studies'),
('London Film School'),
('London Institute of Shipping & Transport'),
('London Metropolitan University'),
('London Reading College'),
('London School of Accountancy & Management'),
('London School of Business and Finance'),
('London School of Business and Management'),
('London School of Jewish Studies'),
('London School of Theology'),
('London South Bank University'),
('Loughborough University'),
('Manchester International College'),
('Manchester Metropolitan University'),
('Maritime Greenwich College'),
('Memorial University of Newfoundland, Harlow, Essex, England'),
('Middlesex University, London'),
('National Film and Television School'),
('New London College'),
('New York University'),
('Newcastle Academy of Business & Technology'),
('Newcastle University'),
('Newman University, Birmingham'),
('Northumbria University, Newcastle upon Tyne'),
('Norwich University of the Arts'),
('Nottingham Trent University'),
('Oxford Brookes University'),
('Oxford College of London'),
('Oxford House College'),
('Pepperdine University'),
('Plymouth College of Art and Design'),
('Queen Margaret University, Edinburgh'),
('Queens University'),
('Queens University Belfast'),
('Ravensbourne College of Design and Communication'),
('Rayat London College'),
('Regal International College'),
('Regents College'),
('Richmond University, Essex'),
('Richmond, The American International University in London'),
('Roehampton University, London'),
('Rose Bruford College'),
('Royal Agricultural University, Cirencester'),
('Royal College of Art, London'),
('Royal College of Music'),
('Royal Northern College of Music'),
('Royal Scottish Academy of Music and Drama'),
('Royal Welsh College of Music & Drama'),
('Ruskin College'),
('SAE Institute'),
('Schiller International University, London'),
('Scottish Agricultural College'),
('Sheffield Hallam University'),
('Sothebys Institute of Art'),
('Southampton Solent University'),
('St. Marys University College (Belfast)'),
('St. Marys University College (Twickenham)'),
('Staffordshire University'),
('Stranmillis University College'),
('Swansea Metropolitan University'),
('Swansea University'),
('Syracuse University'),
('Taitec Manchester'),
('Tech Music Schools'),
('Teesside University'),
('The Arts University Bournemouth'),
('The College of Law'),
('The Open University, Milton Keynes'),
('The Princes Drawing School'),
('The Princes School of Traditional Arts'),
('The Robert Gordon University, Aberdeen'),
('The Woolf Institute of Abrahamic Faiths, Wesley House, Cambridge'),
('Trinity Laban Conservatoire of Music and Dance'),
('UHI Millennium Institute'),
('University Campus Suffolk'),
('University Centre at Blackburn College, Blackburn'),
('University College Birmingham'),
('University for the Creative Arts'),
('University of Aberdeen'),
('University of Abertay Dundee'),
('University of Bath'),
('University of Bedfordshire'),
('University of Birmingham'),
('University of Bolton'),
('University of Bradford'),
('University of Brighton'),
('University of Bristol'),
('University of Buckingham'),
('University of Cambridge'),
('University of Central Lancashire, Preston'),
('University of Chester'),
('University of Chichester'),
('University of Crown at Port Din.'),
('University of Cumbria, Carlisle'),
('University of Delaware'),
('University of Derby'),
('University of Dundee'),
('University of East Anglia, Norwich'),
('University of East London'),
('University of Edinburgh'),
('University of Essex'),
('University of Exeter'),
('University of Glasgow'),
('University of Gloucestershire'),
('University of Greenwich'),
('University of Hertfordshire, Hatfield'),
('University of Huddersfield'),
('University of Hull'),
('University of Kent'),
('University of Leeds'),
('University of Leicester'),
('University of Lincoln'),
('University of Liverpool'),
('University of London'),
('University of Manchester'),
('University of Northampton'),
('University of Notre Dame'),
('University of Nottingham'),
('University of Oxford'),
('University of Plymouth'),
('University of Portsmouth'),
('University of Reading'),
('University of Salford'),
('University of Sheffield'),
('University of South Wales'),
('University of Southampton'),
('University of St Andrews'),
('University of St Mark & St John, Plymouth'),
('University of Stirling, Bridge of Allan'),
('University of Strathclyde, Glasgow'),
('University of Sunderland'),
('University of Surrey, Guildford'),
('University of Sussex'),
('University of the Arts London'),
('University of the Highlands & Islands, Inverness'),
('University of the West of England, Bristol'),
('University of the West of Scotland'),
('University of Ulster'),
('University of Wales'),
('University of Wales, Trinity Saint David'),
('University of Warwick, Coventry'),
('University of West London'),
('University of Westminster, London'),
('University of Winchester'),
('University of Wisconsin System, Dalkeith Palace, Midlothian, Scotland'),
('University of Wolverhampton'),
('University of Worcester'),
('University of York'),
('Wessex Institute of Technology'),
('Western Governors Graduate School'),
('Writtle College'),
('York St John University');